const bcrypt = require("bcryptjs");
const prisma = require("../src/models/prisma");

const password = bcrypt.hashSync("!aA123");

const roleData = [{ roleName: "ADMIN" }, { roleName: "USER" }];

const userData = [
  {
    firstName: "Baki",
    lastName: "Hanma",
    email: "user1@ifcg.co.th",
    isActive: true,
    password,
  },
  {
    firstName: "Yujiro",
    lastName: "Hanma",
    email: "user2@ifcg.co.th",
    isActive: true,
    password,
  },
  {
    firstName: "Jack",
    lastName: "Hanma",
    email: "user3@ifcg.co.th",
    isActive: false,
    password,
  },
  {
    firstName: "Doppo",
    lastName: "Orochi",
    email: "user4@ifcg.co.th",
    isActive: true,
    password,
  },
  {
    firstName: "Gouki",
    lastName: "Shibukawa",
    email: "user5@ifcg.co.th",
    isActive: true,
    password,
  },
  {
    firstName: "Biscuit",
    lastName: "Oliva",
    email: "user6@ifcg.co.th",
    isActive: false,
    password,
  },
  {
    firstName: "Retsu",
    lastName: "Kaioh",
    email: "user7@ifcg.co.th",
    isActive: true,
    password,
  },
];

const userRoleData = [
  {
    assignedAt: new Date(),
    userId: 1,
    roleId: 1,
  },
  {
    assignedAt: new Date(),
    userId: 1,
    roleId: 2,
  },
  {
    assignedAt: new Date(),
    userId: 2,
    roleId: 1,
  },
  {
    assignedAt: new Date(),
    userId: 3,
    roleId: 2,
  },
  {
    assignedAt: new Date(),
    userId: 4,
    roleId: 2,
  },
  {
    assignedAt: new Date(),
    userId: 5,
    roleId: 2,
  },
  {
    assignedAt: new Date(),
    userId: 6,
    roleId: 2,
  },
  {
    assignedAt: new Date(),
    userId: 7,
    roleId: 2,
  },
];

const quotationData = [
  {
    id: 1,
    userId: 1,
    customerFirstName: "ธงชัย",
    customerLastName: "เกษมสันต์",
    customerMobile: "0891234567",
    projectName: "The Issara Sathorn",
    roomNo: "B1503",
    roomFloor: "15",
    roomType: "1BR",
    roomSize: 29.58,
    roomDiscount: 350000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 500,
    commonFee: 80,
    customerEmail: "thongchai_kasem@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 2,
    userId: 1,
    customerFirstName: "อรวรรณ",
    customerLastName: "บุญศรี",
    customerMobile: "0887654321",
    projectName: "Chewathai Hallmark Ladpro Chokchai4",
    roomNo: "A0207",
    roomFloor: "2",
    roomType: "studio",
    roomSize: 22.34,
    roomDiscount: 120000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 400,
    commonFee: 90,
    customerEmail: "orawan_boonsee@gmail.com",
    status: "COMPLETED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 3,
    userId: 2,
    customerFirstName: "วีระ",
    customerLastName: "ชัยสมบัติ",
    customerMobile: "0812345678",
    projectName: "Wish Signature II Midtown Siam",
    roomNo: "C3301",
    roomFloor: "33",
    roomType: "2BR+",
    roomSize: 65.23,
    roomDiscount: 240000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 750,
    commonFee: 110,
    customerEmail: "wera_chaisombat@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 4,
    userId: 3,
    customerFirstName: "นภาพร",
    customerLastName: "วรรณสุข",
    customerMobile: "0898765432",
    projectName: "Park Origin Payathai",
    roomNo: "D2505",
    roomFloor: "25",
    roomType: "1BR+",
    roomSize: 34.12,
    roomDiscount: 190000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 600,
    commonFee: 70,
    customerEmail: "napaporn_wansook@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 5,
    userId: 4,
    customerFirstName: "พีระ",
    customerLastName: "สมบัติ",
    customerMobile: "0876543210",
    projectName: "Altitude Symphony Charoenkrung",
    roomNo: "E0408",
    roomFloor: "4",
    roomType: "2BR",
    roomSize: 42.56,
    roomDiscount: 370000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 450,
    commonFee: 100,
    customerEmail: "peera_sombat@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 6,
    userId: 5,
    customerFirstName: "สมชาย",
    customerLastName: "พรหมเทพ",
    customerMobile: "0891122334",
    projectName: "Wish Signature II Midtown Siam",
    roomNo: "A0307",
    roomFloor: "3",
    roomType: "studio",
    roomSize: 23.45,
    roomDiscount: 150000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 350,
    commonFee: 75,
    customerEmail: "somchai_promthep@gmail.com",
    status: "COMPLETED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 7,
    userId: 6,
    customerFirstName: "สายชล",
    customerLastName: "สวัสดิ์วัฒน์",
    customerMobile: "0883344556",
    projectName: "The Issara Sathorn",
    roomNo: "B1410",
    roomFloor: "14",
    roomType: "1BR",
    roomSize: 30.56,
    roomDiscount: 250000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 500,
    commonFee: 85,
    customerEmail: "saichon_sawatwat@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 8,
    userId: 7,
    customerFirstName: "ภัทร",
    customerLastName: "เทวารักษ์",
    customerMobile: "0874455667",
    projectName: "Chewathai Hallmark Ladpro Chokchai4",
    roomNo: "C0212",
    roomFloor: "2",
    roomType: "2BR+",
    roomSize: 55.32,
    roomDiscount: 300000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 700,
    commonFee: 95,
    customerEmail: "pat_thewarak@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 9,
    userId: 7,
    customerFirstName: "ดนัย",
    customerLastName: "สิริชัย",
    customerMobile: "0895566778",
    projectName: "Park Origin Payathai",
    roomNo: "D0909",
    roomFloor: "9",
    roomType: "1BR+",
    roomSize: 34.89,
    roomDiscount: 120000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 400,
    commonFee: 50,
    customerEmail: "danai_sirichai@gmail.com",
    status: "COMPLETED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 10,
    userId: 1,
    customerFirstName: "ประภา",
    customerLastName: "จันทรเสวี",
    customerMobile: "0866677889",
    projectName: "Altitude Symphony Charoenkrung",
    roomNo: "E2020",
    roomFloor: "20",
    roomType: "penthouse",
    roomSize: 90.34,
    roomDiscount: 450000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 750,
    commonFee: 110,
    customerEmail: "prapa_jantrasewee@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 11,
    userId: 2,
    customerFirstName: "สมชาย",
    customerLastName: "พรหมเทพ",
    customerMobile: "0891122334",
    projectName: "Wish Signature II Midtown Siam",
    roomNo: "A0307",
    roomFloor: "3",
    roomType: "studio",
    roomSize: 23.45,
    roomDiscount: 150000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 350,
    commonFee: 75,
    customerEmail: "somchai_promthep@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 12,
    userId: 1,
    customerFirstName: "สายชล",
    customerLastName: "สวัสดิ์วัฒน์",
    customerMobile: "0883344556",
    projectName: "The Issara Sathorn",
    roomNo: "B1410",
    roomFloor: "14",
    roomType: "1BR",
    roomSize: 30.56,
    roomDiscount: 250000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 500,
    commonFee: 85,
    customerEmail: "saichon_sawatwat@gmail.com",
    status: "COMPLETED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 13,
    userId: 1,
    customerFirstName: "ภัทร",
    customerLastName: "เทวารักษ์",
    customerMobile: "0874455667",
    projectName: "Chewathai Hallmark Ladpro Chokchai4",
    roomNo: "C0212",
    roomFloor: "2",
    roomType: "2BR+",
    roomSize: 55.32,
    roomDiscount: 300000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 700,
    commonFee: 95,
    customerEmail: "pat_thewarak@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 14,
    userId: 1,
    customerFirstName: "ดนัย",
    customerLastName: "สิริชัย",
    customerMobile: "0895566778",
    projectName: "Park Origin Payathai",
    roomNo: "D0909",
    roomFloor: "9",
    roomType: "1BR+",
    roomSize: 34.89,
    roomDiscount: 120000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 400,
    commonFee: 50,
    customerEmail: "danai_sirichai@gmail.com",
    status: "COMPLETED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 15,
    userId: 1,
    customerFirstName: "ประภา",
    customerLastName: "จันทรเสวี",
    customerMobile: "0866677889",
    projectName: "Altitude Symphony Charoenkrung",
    roomNo: "E2020",
    roomFloor: "20",
    roomType: "penthouse",
    roomSize: 90.34,
    roomDiscount: 450000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 750,
    commonFee: 110,
    customerEmail: "prapa_jantrasewee@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 16,
    userId: 1,
    customerFirstName: "ประภา",
    customerLastName: "จันทรเสวี",
    customerMobile: "0866677889",
    projectName: "Altitude Symphony Charoenkrung",
    roomNo: "E2020",
    roomFloor: "20",
    roomType: "penthouse",
    roomSize: 90.34,
    roomDiscount: 450000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 750,
    commonFee: 110,
    customerEmail: "prapa_jantrasewee@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 17,
    userId: 1,
    customerFirstName: "วิศรุต",
    customerLastName: "บัวแก้ว",
    customerMobile: "0893344556",
    projectName: "The Issara Sathorn",
    roomNo: "D1512",
    roomFloor: "15",
    roomType: "2BR",
    roomSize: 42.68,
    roomDiscount: 350000,
    bookingPayment: 50000,
    downPayment: 100000,
    sinkingFund: 600,
    commonFee: 85,
    customerEmail: "wisarut_buakaew@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
  {
    id: 18,
    userId: 1,
    customerFirstName: "วิชัย",
    customerLastName: "ทองคำ",
    customerMobile: "0875566778",
    projectName: "Wish Signature II Midtown Siam",
    roomNo: "A1205",
    roomFloor: "12",
    roomType: "1BR+",
    roomSize: 34.56,
    roomDiscount: 120000,
    bookingPayment: 100000,
    downPayment: 100000,
    sinkingFund: 450,
    commonFee: 75,
    customerEmail: "wichai_thongkam@gmail.com",
    status: "DRAFTED",
    pdfLink:
      "https://res.cloudinary.com/dbtdl98jn/raw/upload/v1718352247/quotations/hpbmlwh0tryuffjvmktg.pdf",
  },
];

const run = (asyc = async () => {
  await prisma.role.createMany({ data: roleData });
  await prisma.user.createMany({ data: userData });
  await prisma.userRole.createMany({ data: userRoleData });
  await prisma.quotation.createMany({ data: quotationData });
});

run();
